### ISSUE TITLE
With large font sizes you cannot click some lines.

### ISSUE THREAD

**Issue by ruapotato** [CribberSix/pygame-texteditor#10]
When I used set_font_size(45) I could not select lines past what the default text would have rendered.

Tested on Debian using pip:  pygame-texteditor-0.6.7, pyperclip-1.8.2

**Comment by CribberSix** [comment]
I will have a look at it in the coming days, thanks for raising this issue!

**Comment by CribberSix** [comment]
Will be solved in the upcoming release.

**Comment by CribberSix** [comment]
Fixed in 0.7: https://pypi.org/project/pygame-texteditor/0.7.0/
