### ISSUE TITLE
Line number cut off with large fount sizes

### ISSUE THREAD

**Issue by ruapotato** [CribberSix/pygame-texteditor#11]
When I used set_font_size(45) line numbers get cut off:
![image](https://user-images.githubusercontent.com/13055763/179435605-005f6aa0-3fbe-4974-b787-389f57b93cec.png)

Tested on Debian using pip: pygame-texteditor-0.6.7, pyperclip-1.8.2

**Comment by CribberSix** [comment]
I will have a look at it in the coming days, thanks for raising this issue!

**Comment by CribberSix** [comment]
Will be solved in the upcoming release.

**Comment by CribberSix** [comment]
Fixed in 0.7: https://pypi.org/project/pygame-texteditor/0.7.0/
