### ISSUE TITLE
Fixed - Bump versions

### ISSUE THREAD

**Issue by Gaming32** [CribberSix/pygame-texteditor#2]
My request is to update the version of the packages (or pygame at least) or completely remove the version specifier. This is because I use pygame 2.X and I think it would be useful to use this library no matter what version of pygame one uses.

**Comment by CribberSix** [comment]
Removing the version specifier won't help, pygame 2.x differs concerning the visual engine from 1.9.x versions. I might have a look at the changelogs in the next two weeks, but I can't promise anything as I'm busy with work right now.

**Comment by Gaming32** [comment]
I haven't noticed any changes in the API, even though what happens is different (use GPU rendering instead of the CPU)

**Comment by CribberSix** [comment]
I found time today to look through the changes and the stuff that is not yet backwards compatible (yet - they are working on it) is of no relevance to this package. So I bumped the version requirement - you can  upgrade the package with `pip install --upgrade pygame-texteditor`. Thanks for your input and happy coding!
