### ISSUE TITLE
show cursor ?

### ISSUE THREAD

**Issue by pmp-p** [CribberSix/pygame-texteditor#7]
Hi, the readme does not show how to setup a blinking or static block cursor, but i think it is very important

And by the way i would like to ask your permission to use/display/modify/package both pygame-texteditor and  pygame-markdown for Pygame wasm tech demo ( https://pmp-p.github.io/pygame-wasm/  https://pypi.org/project/pygbag/ )

**Comment by CribberSix** [comment]
As of now there is no option to have a static block cursor, but I could add it in the next weeks - I will see when I get around to it. 

Both packages, `pygame-markdown` and `pygame-texteditor` are published under the MIT license, meaing you can "**use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software**" as you please. I would appreciate mentioning my name but even that is optional. The only limitation is that the MIT copyright notice has to be included in all copies/substantial portions of the software, see the LICENSE.md for more details (or google how MIT-Licenses work).

**Comment by CribberSix** [comment]
Added the functionality in [v0.6.7](https://pypi.org/project/pygame-texteditor/0.6.7/). You can switch the mode now as follows:

TX.set_cursor_mode("static")
TX.set_cursor_mode("blinking")

Default is "blinking".
